'''
Importing Preprocessed Data to Database
This module provides methods to interact with the "assessment_service.py" module to import parsed, preprocessed data into the database.
'''
# import the data tables generated by qiime2_preproc.py into the database
# import the representative sequences file path generated by qiime2_preproc.py into the database
import pandas as pd
import re

# parse genus-table.tsv for the genus table
'''
parses data into the following format:
run_id: str, rows: list[tuple[str, float]]
example:
run_id='SRR35606904', row=[('Bacteroides', 0.11231697090885635), ('Faecalibacterium', 0.15345417016061408), ...]
'''
def clean_genus(tax_string):
    parts = tax_string.split(";")
    genus_part = None
    for p in parts:
        if p.startswith("g__"):
            genus_part = p
            break

    if genus_part is None:
        return "Unclassified"

    genus = genus_part.replace("g__", "").strip()
    genus = re.sub(r"[\[\]]", "", genus)

    if genus == "" or genus.lower() in [
        "uncultured", "unknown", "incertae_sedis"
    ]:
        return "Unclassified"

    return genus

def parse_genus_table(genus: str):
    # reformat the table
    abundance = pd.read_csv(genus, sep="\t", skiprows=1)
    abundance.rename(columns={'#OTU ID': 'genus'}, inplace=True)

    # extract genus from taxonomy string and rename
    abundance['genus'] = abundance['genus'].apply(clean_genus)
    
    # construct a dictionary of column name (srr): list of tuples (genus, abundance)
    records = {}
    for col in abundance.columns[1:]:
        records[col] = [(row['genus'], row[col]) for _, row in abundance.iterrows()]

    return records


# parse reps-seq.fasta and taxonomy.tsv for feature table
'''
parses data into the following format:
features: list[dict]
example:
features=[{'sequence': 'TGGGCGAGAGCCTGAACCAGCCAAGTAGCGTG', 
           'feature_id': '21f4de567ca86c973a9a0d07ed17e3d2', 
           'taxonomy': 'd__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella_9;s__'}]
'''
def parse_feat_tax_seqs(tax: str, seqs: str):
    # get the dataframe
    taxonomy = pd.read_csv(tax, sep='\t')

    # get a list of dictionaries containing associated sequences, feature ids, and taxonomies
    feature_seqs = []
    with open(seqs, mode="r") as s:
        lines = s.readlines()
        lines_feature_id = lines[::2] # feature id lines at even indices
        lines_sequence = lines[1::2] # sequence lines at odd indices
        for feature_id, sequence in zip(lines_feature_id, lines_sequence):
            condition = taxonomy['Feature ID'] == feature_id[1:].strip()
            taxon = taxonomy.loc[condition, 'Taxon']
            feature_seqs.append({
                'sequence': sequence.strip(),
                'feature_id': feature_id[1:].strip(),
                'taxonomy': taxon.iloc[0] if not taxon.empty else None
            })

    return feature_seqs


# parse feature-table.tsv
'''
parses data into the following format:
run_id: str, rows: list[tuple[str, int]]
example:
run_id='SRR35606904', rows=[('21f4de567ca86c973a9a0d07ed17e3d2', 4655), ('9cc977b5dee75ca96f18928722049c50', 3818), ...]
'''
def parse_feature_counts(feat: str):
    # get the dataframe
    feature_table = pd.read_csv(feat, sep='\t', skiprows=1)
    feature_table.rename(columns={'#OTU ID': 'feature_id'}, inplace=True)

    # get a dictionary of column_name (srr): list of tuples (feature_id, raw abundance counts)
    features = {}
    for col in feature_table.columns[1:]:
        features[col] = [(row['feature_id'], row[col]) for _, row in feature_table.iterrows()]

    return features